// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// heapify_c
NumericMatrix heapify_c(NumericMatrix A, int i, int heap_size);
RcppExport SEXP _MMDOrdering_heapify_c(SEXP ASEXP, SEXP iSEXP, SEXP heap_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type heap_size(heap_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(heapify_c(A, i, heap_size));
    return rcpp_result_gen;
END_RCPP
}
// build_heap_c
NumericMatrix build_heap_c(NumericMatrix A);
RcppExport SEXP _MMDOrdering_build_heap_c(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(build_heap_c(A));
    return rcpp_result_gen;
END_RCPP
}
// heapsort_c
NumericMatrix heapsort_c(NumericMatrix A);
RcppExport SEXP _MMDOrdering_heapsort_c(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(heapsort_c(A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MMDOrdering_heapify_c", (DL_FUNC) &_MMDOrdering_heapify_c, 3},
    {"_MMDOrdering_build_heap_c", (DL_FUNC) &_MMDOrdering_build_heap_c, 1},
    {"_MMDOrdering_heapsort_c", (DL_FUNC) &_MMDOrdering_heapsort_c, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MMDOrdering(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
