# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heapify_c <- function(A, i, heap_size) {
    .Call('_MMDOrdering_heapify_c', PACKAGE = 'MMDOrdering', A, i, heap_size)
}

build_heap_c <- function(A) {
    .Call('_MMDOrdering_build_heap_c', PACKAGE = 'MMDOrdering', A)
}

heapsort_c <- function(A) {
    .Call('_MMDOrdering_heapsort_c', PACKAGE = 'MMDOrdering', A)
}

