# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heapify_c <- function(points, index, heap_size) {
    .Call('_MMDOrdering_heapify_c', PACKAGE = 'MMDOrdering', points, index, heap_size)
}

build_heap_c <- function(points) {
    .Call('_MMDOrdering_build_heap_c', PACKAGE = 'MMDOrdering', points)
}

heapsort_c <- function(points) {
    .Call('_MMDOrdering_heapsort_c', PACKAGE = 'MMDOrdering', points)
}

